apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask
        image: flask-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # Resource limits for better resource management
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Health checks for reliability
        livenessProbe:
          # Check if container is alive - restart if this fails
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10  # Wait 10s after startup
          periodSeconds: 30        # Check every 30s
          timeoutSeconds: 5        # Timeout after 5s
          failureThreshold: 3      # Restart after 3 failures
        readinessProbe:
          # Check if container is ready for traffic
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5   # Check readiness after 5s
          periodSeconds: 10        # Check every 10s
          timeoutSeconds: 3        # Timeout after 3s
          failureThreshold: 3      # Mark unready after 3 failures
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007