apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask
        image: flask-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 5000          
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
